## <center>CSE 546: Reinforcement Learning</center>
### <center>Prof. Alina Vereshchaka</center>
<!-- ### <center>Fall 2022</center> -->

Welcome to the Assignment 2, Part 1: Introduction to Deep Reinforcement Learning and Neural Networks! The goal of this assignment is to make you comfortable with the application of different Neural Network structures depending on how the Reinforcement Learning environment is set up.

In [ ]:
!unzip images.zip

Archive:  images.zip
   creating: images/
  inflating: __MACOSX/._images       
  inflating: images/wumpus_dead.png  
  inflating: __MACOSX/images/._wumpus_dead.png  
  inflating: images/agent_alive_wumpus_dead.png  
  inflating: __MACOSX/images/._agent_alive_wumpus_dead.png  
  inflating: images/agent_dead_wumpus_alive.png  
  inflating: __MACOSX/images/._agent_dead_wumpus_alive.png  
  inflating: images/agent.png        
  inflating: __MACOSX/images/._agent.png  
  inflating: images/breeze_gold.png  
  inflating: __MACOSX/images/._breeze_gold.png  
  inflating: images/wumpus.png       
  inflating: __MACOSX/images/._wumpus.png  
  inflating: images/agent_dead_pit.png  
  inflating: __MACOSX/images/._agent_dead_pit.png  
  inflating: images/breeze_gold_stench.png  
  inflating: __MACOSX/images/._breeze_gold_stench.png  
  inflating: images/environment_render.png  
  inflating: __MACOSX/images/._environment_render.png  
   creating: images/neural_network_structures/
  inflating: __MACO

In [4]:
# Imports
from environment import WumpusWorldEnvironment

# Environment

We will be working with an implementation of the Wumpus World environment. The environment comes from the book "Artificial Intelligence: A Modern Approach" by Stuart J. Russell and Peter Norvig. 

### ENVIRONMENT DETAILS:

The environment is a 6 x 6 grid world containing a total of 36 grid blocks. 

#### ENVIRONMENT OBJECTS:
The environment consists of the following objects:

1. **Agent** - The agent starts in the grid block at the bottom left corner whose co-ordinates are [0, 0]. The goal of our agent is to collect the Gold while avoiding the Wumpus and the pits. 

2. **Wumpus** - The monster which would eat the agent if they are in the same grid block.

3. **Pit** - The agent must avoid falling into the pits. 

4. **Gold** - The agent must collect the Gold.

5. **Breeze** - Breeze surrounds the Pits and warn the agent of a Pit in an adjacent grid block.

6. **Stench** - Stench surrounds the Wumpus and warns the agent of the Wumpus in an adjacent grid block.

#### ENVIRONMENT OBSERVATIONS:

Our implementation of the environment provides you with four different types of observations:

1. **Integer** - Integer in the range [0 - 35]. This represents the grid block the agent is in. E.g., if the agent is in the bottom left grid block (starting position) the observation would be 0, if the agent is in the grid block containing the Gold the observation would be 34, if the agent is in the top right grid block the observation would be 35.

2. **Vector** - 

    **2.1.** A vector of length 2 representing the agent co-ordinates. The first entry represents the x co-ordinate and the second entry represets the y co-ordinate. E.g., if the agent is in the bottom left grid block (starting position) the observation would be [0, 0], if the agent is in the grid block containing the Gold the observation would be [4, 5], if the agent is in the top right grid block the observation would be [5, 5].
    
    **2.2.** A vector of length 36 representing the one-hot encoding of the integer observation (refer type 1 above). E.g., if the agent is in the bottom left grid block (starting position) the observation would be [1, 0, ..., 0, 0], if the agent is in the grid block containing the Gold the observation would be [0, 0, ..., 1, 0], if the agent is in the top right grid block the observation would be [0, 0, ..., 0, 1].


3. **Image** - Image render of the environment returned as an NumPy array. The image size is 84 * 84 (same size used in the DQN paper). E.g., if the agent is in the bottom right grid block the observation is:

    Observation: (84 * 84)

     [[255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     ...

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]]

    Observation type: <class 'numpy.ndarray'>

    Observation Shape: (84, 84)

    Visually, it looks like:
    <img src="./images/environment_render.png" width="500" height="500">
    

4. **Float** - Float in the range [0 - $\infty$] representing the time elapsed in seconds. 

#### ENVIRONMENT ACTIONS:

Our implementation of the environment provides you with three different types of actions:

1. **Discrete** - Integer in the range [0 - 3] representing the four actions possible in the environment as follows: 0 - Right 1 - Left 2 - Up 3 - Down.

2. **Multi-Discrete** - Array of length four where each element takes binary values 0 or 1. Array elements represent if we take a particular action. Array element with index 0 corresponds to the right action, index 1 corresponds to the left action, index 2 corresponds to the up action, and index 3 corresponds to the down action. E.g., 
   action = [1, 0, 0, 0] would result in the agent moving right.
   action = [1, 0, 1, 0] would result in the agent moving right and up.
   action = [0, 1, 0, 1] would result in the agent moving left and down.

3. **Continuous** - Float in the range [-1, 1] determining whether the agent will go left, right, up, or down as follows:

    if -1 <= action <= -0.5:
        Go Right.
    elif -0.5 < action <= 0:
        Go Left.
    elif 0 < action <= 0.5:
        Go Up.
    elif 0.5 < action <= 1:
        Go Down.
        
### YOUR TASK IS TO USE A NEURAL NETWORK TO WORK WITH ALL FOUR TYPES OF OBSERVATIONS AND ALL THREE TYPES OF  ACTIONS.

<img src="./images/wumpus_world_environment.jpg" width="600" height="600">

# START COMPLETING YOUR ASSIGNMENT HERE

## Observation Type - Integer, Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is an integer (refer to environment observations type 1). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_1_64_4.png">

In [5]:
!rm -rf __MACOSX/

In [6]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""
import tensorflow.keras as tfk
import tensorflow as tf
import numpy as np
environment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation = environment.reset()

# BEGIN_YOUR_CODE
model = tfk.Sequential([
    tfk.layers.Input(1),
    tfk.layers.Dense(64,activation='relu'),
    tfk.layers.Dense(4,activation='linear')
])

# END_YOUR_CODE
model.compile()


In [7]:
done = False
obs = observation
q_table = model.predict([obs])
z = np.argmax(q_table)
observation, _ , done ,info = environment.step(z)
print(obs, q_table)
  



1/1 [==============================] - 0s 320ms/step
0 [[0. 0. 0. 0.]]


## Observation Type - Vector (2.1), Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 2 (refer to environment observations type 2.1). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_2_64_4.png">

In [8]:
obs

0

In [10]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='vector', action_type='discrete')
observation = environment.reset()

# BEGIN_YOUR_CODE
model = tfk.Sequential([
    tfk.layers.Input(shape=(2)),
    tfk.layers.Dense(64,activation='relu'),
    tfk.layers.Dense(4,activation='linear')
])

model.compile()
obs = observation.reshape((1,2))
q_table = model.predict(obs)
print(obs, q_table)

# END_YOUR_CODE

1/1 [==============================] - 0s 54ms/step
[[0 0]] [[0. 0. 0. 0.]]


## Observation Type - Vector (2.2), Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector.

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_4.png">

In [11]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation = environment.reset()

# BEGIN_YOUR_CODE
model = tfk.Sequential([
    tfk.layers.Input(shape=(36)),
    tfk.layers.Dense(64,activation='relu'),
    tfk.layers.Dense(4,activation='linear')
])

model.compile()

print(observation)
rand = [0]*36
rand[observation] = 1
observation = np.array(rand)
obs = observation.reshape((1,36))
q_table = model.predict(obs)
print(obs, q_table)

# END_YOUR_CODE

0
1/1 [==============================] - 0s 59ms/step
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]] [[-0.06991051 -0.09714556  0.07881412  0.01357894]]


## Observation Type - Image, Action Type - Discrete

The part of the assignment requires you to create a convolutional neural network with one convolutional layer having 128 filters of size 3 x 3, one hidden layer having 64 neurons, and the output layer having 4 neurons. The input to the neural network is an image of size 84 * 84 (refer to environment observations type 3). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/convolutional_neural_network_84x84_128_64_4.png">

In [12]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='image', action_type='discrete')
observation = environment.reset()

# BEGIN_YOUR_CODE
model = tfk.Sequential([
    tfk.layers.Conv2D(128, kernel_size=(3,3), input_shape=(84,84,1)),
    tfk.layers.Flatten(),
    tfk.layers.Dense(64,activation='relu'),
    tfk.layers.Dense(4,activation='linear')
])

model.compile()

# END_YOUR_CODE

In [13]:
from pprint import pprint
print(observation.shape)
obs = observation.reshape((1,84,84,1))
q_table = model.predict(obs)
pprint(observation)
pprint(q_table)

(84, 84)
1/1 [==============================] - 0s 179ms/step
array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)
array([[-109.01348 ,  -63.412777,   59.522778,  103.8623  ]],
      dtype=float32)


## Observation Type - Float, Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a float (refer to environment observations type 4). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_1_64_4.png">

In [14]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='float', action_type='discrete')
observation = environment.reset()

# BEGIN_YOUR_CODE
model = tfk.Sequential([
    tfk.layers.Input(1),
    tfk.layers.Dense(64,activation='relu'),
    tfk.layers.Dense(4,activation='linear')
])

model.compile()

obs = observation
q_table = model.predict([obs])
print(obs, q_table)

# END_YOUR_CODE

1/1 [==============================] - 0s 73ms/step
0.0001125335693359375 [[ 1.0426677e-05 -4.0380364e-06 -4.7218495e-05  1.2274836e-05]]


## Observation Type - Vector (2.2), Action Type - Multi-Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an array representing the probability of choosing the actions. (If the value of the array element is >=0.5 you will perform the action.) (refer to environment actions type 2).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector.

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_4_sigmoid.png">

In [15]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted action probabilities for the four actions. Print the observation and the action probabilities."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='multi_discrete')
observation = environment.reset()

# BEGIN_YOUR_CODE
model = tfk.Sequential([
    tfk.layers.Input(shape=(36)),
    tfk.layers.Dense(64,activation='relu'),
    tfk.layers.Dense(4,activation='sigmoid')
])

model.compile()

print(observation)
rand = [0]*36
rand[observation] = 1
observation = np.array(rand)
obs = observation.reshape((1,36))
q_table = model.predict(obs)
print(obs, q_table)
# END_YOUR_CODE

0
1/1 [==============================] - 0s 62ms/step
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]] [[0.45909357 0.53417385 0.5548418  0.55524266]]


## Observation Type - Vector (2.2), Action Type - Continuous

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 1 neuron. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an float in the range [-1, 1] determining the action which will be taken. (refer to environment actions type 3).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector and use the TanH activation function to get the output in the range [-1, 1].

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_1.png">

In [17]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted action. Print the observation and the predicted action."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='continuous')
observation = environment.reset()

# BEGIN_YOUR_CODE
model = tfk.Sequential([
    tfk.layers.Input(shape=(36)),
    tfk.layers.Dense(64,activation='relu'),
    tfk.layers.Dense(1,activation='tanh')
])

model.compile()

print(observation)
rand = [0]*36
rand[observation] = 1
observation = np.array(rand)
obs = observation.reshape((1,36))
predicted_value = model.predict(obs)
print(obs, predicted_value)

# END_YOUR_CODE

0
1/1 [==============================] - 0s 82ms/step


/usr/local/lib/python3.9/dist-packages/gym/spaces/box.py:128: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]] [[0.00140826]]
